const $=s=>document.querySelector(s);
let packageId=null,runId=null,poll=null,ticker=null,preview=null;
const names={executive:'Главное и решения',analytical:'Данные и доказательства',story:'Контекст и развитие'};
function el(tag,cls,text){const node=document.createElement(tag);if(cls)node.className=cls;if(text!==undefined)node.textContent=text;return node;}
function toast(text){$('#toast').textContent=text;$('#toast').hidden=false;setTimeout(()=>$('#toast').hidden=true,12000);}
async function api(path,options={}){const r=await fetch(path,options);const result=await r.json();if(!r.ok)throw Error(typeof result.detail==='string'?result.detail:JSON.stringify(result.detail));return result;}
const jsonPost=(path,data)=>api(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});
const fileUrl=(id,name)=>`/api/jobs/${id}/files/${name}`;
function warningList(items){const node=el('div','warnings');items.forEach(x=>node.append(el('p','',x)));return node;}
function setProgress(id,value,label){$(id+' span').style.width=value+'%';$(id+' p').textContent=label;}
function dirty(){packageId=null;$('#generate-button').disabled=true;}
$('#prepare-form').addEventListener('input',dirty);
$('#content').addEventListener('input',()=>$('#char-count').textContent=$('#content').value.length.toLocaleString('ru')+' символов');
$('#reference').addEventListener('change',()=>{dirty();$('#dropzone').hidden=!!$('#reference').value;if($('#reference').value)$('#template').value='';});
$('#template').addEventListener('change',()=>{if($('#template').files.length){$('#reference').value='';$('#file-label').textContent=$('#template').files[0].name;}dirty();});
for(const type of ['dragover','dragleave','drop'])$('#dropzone').addEventListener(type,event=>{event.preventDefault();$('#dropzone').classList.toggle('dragover',type==='dragover');if(type==='drop'&&event.dataTransfer.files.length){$('#template').files=event.dataTransfer.files;$('#template').dispatchEvent(new Event('change'));}});
function displayProfile(job){packageId=job.id;$('#profile-empty').hidden=true;$('#prep-progress').hidden=true;$('#profile').hidden=false;$('#profile').replaceChildren();const t=job.template;$('#profile').append(el('div','profile-name',t.name));const sw=el('div','swatches');t.colors.slice(0,7).forEach(c=>{const n=el('span','swatch');n.style.background=c;n.title=c;sw.append(n);});$('#profile').append(sw);const stats=el('div','profile-stats');[[t.slide_count,'слайдов изучено'],[t.patterns.length,'примеров композиций'],[t.layout_count,'макетов']].forEach(([v,l])=>{const n=el('div');n.append(el('strong','',v),el('small','',l));stats.append(n);});$('#profile').append(stats,el('p','profile-detail',`Шрифт: ${t.font} (${t.font_origin?.kind==='embedded'?'из PPTX':'локальный'}) · ${t.width.toFixed(0)} × ${t.height.toFixed(0)} pt`),el('p','profile-detail',`${job.content.facts} фактов · ${job.content.tables} таблиц · ${job.constraints.slides} слайдов на вариант`));const design=el('a','text-button','Открыть DESIGN.md ↗');design.href=fileUrl(job.id,'DESIGN.md');$('#profile').append(design);if(job.warnings?.length)$('#profile').append(warningList(job.warnings));$('#prep-state').textContent='Подготовлено';$('#prep-state').className='pill good';$('#generate-button').disabled=false;$('#step-2').classList.add('active');$('#prepare-button').disabled=false;}
async function watchPreparation(id,autoGenerate=false){clearInterval(poll);const check=async()=>{try{const job=await api(`/api/jobs/${id}`);setProgress('#prep-progress',job.progress||5,job.phase||'Подготовка');if(job.state==='ready'){clearInterval(poll);displayProfile(job);if(autoGenerate)await startGeneration();}else if(job.state==='failed'){clearInterval(poll);$('#prepare-button').disabled=false;$('#prep-state').textContent='Ошибка';$('#prep-state').className='pill error';toast(job.error);}}catch(e){clearInterval(poll);toast(e.message);}};poll=setInterval(check,800);await check();}
$('#prepare-form').addEventListener('submit',async event=>{event.preventDefault();dirty();$('#prepare-button').disabled=true;$('#prep-progress').hidden=false;$('#prep-state').textContent='Анализируем';$('#profile').hidden=true;$('#profile-empty').hidden=true;try{const data=new FormData(event.target);if($('#reference').value)data.delete('template');else data.delete('reference_id');if(!data.get('slides'))data.delete('slides');const job=await api('/api/prepare',{method:'POST',body:data});await watchPreparation(job.id);}catch(e){$('#prepare-button').disabled=false;toast(e.message);}});
function clock(seconds){return `${Math.floor(seconds/60).toString().padStart(2,'0')}:${Math.floor(seconds%60).toString().padStart(2,'0')}`;}
async function startGeneration(){if(!packageId)return;$('#generate-button').disabled=true;$('#prepare-button').disabled=true;$('#generation-status').hidden=false;try{const job=await jsonPost('/api/generate',{package_id:packageId});runId=job.id;clearInterval(ticker);ticker=setInterval(()=>{$('#timer').textContent=clock(Math.max(0,Date.now()/1000-job.created))+' / 05:00';},200);clearInterval(poll);const check=async()=>{try{const state=await api(`/api/jobs/${runId}`);$('#generation-phase').textContent=state.phase||'Запуск';$('#generation-progress').style.width=(state.progress||2)+'%';if(['completed','needs_review','failed','timed_out','cancelled'].includes(state.state)){clearInterval(poll);clearInterval(ticker);$('#generate-button').disabled=false;$('#prepare-button').disabled=false;if(['completed','needs_review'].includes(state.state)){showResults(state);$('#timer').textContent=clock(state.elapsed_seconds)+' / 05:00';}else toast(state.error||'Генерация прервана');}}catch(e){clearInterval(poll);clearInterval(ticker);toast(e.message);}};poll=setInterval(check,850);await check();}catch(e){$('#generate-button').disabled=false;$('#prepare-button').disabled=false;toast(e.message);}}
$('#generate-button').addEventListener('click',startGeneration);
function showResults(job){runId=job.id;packageId=job.package_id;$('#results').hidden=false;$('#step-3').classList.add('active');$('#result-summary').textContent=`${job.variants.reduce((s,v)=>s+v.slides,0)} слайдов · ${job.elapsed_seconds.toFixed(1)} сек. на три варианта · ${job.errors?'есть замечания аудита':'детерминированные проверки пройдены'}${job.model_mode==='extractive'?' · автономный режим':''}`;$('#download-all').href=fileUrl(job.id,'presentations.zip');$('#manifest-link').href=fileUrl(job.id,'manifest.json');$('#result-grid').replaceChildren();$('#audit-list').replaceChildren();for(const variant of job.variants){const card=el('article','result-card');const img=el('img','result-thumb');img.src=fileUrl(job.id,`${variant.key}/slide-1.png`);img.alt=variant.title;img.tabIndex=0;const open=()=>{preview={id:job.id,key:variant.key,count:variant.slides,index:1};$('#preview-title').textContent=variant.title;updatePreview();$('#preview-dialog').showModal();};img.addEventListener('click',open);img.addEventListener('keydown',e=>{if(e.key==='Enter')open();});card.append(img,el('h3','',variant.title),el('div','result-meta',`${variant.slides} слайдов · редактируемый PPTX`));const links=el('div','downloads');for(const fmt of ['pptx','pdf','html']){const a=el('a','',fmt.toUpperCase()+' ↗');a.href=fileUrl(job.id,`${variant.key}/deck.${fmt}`);a.target='_blank';a.rel='noopener';links.append(a);}card.append(links);$('#result-grid').append(card);if(!variant.findings.length)$('#audit-list').append(el('div','audit-line good',`✓ ${variant.title}: ошибок геометрии и покрытия нет`));for(const f of [...variant.findings,...variant.repairs])$('#audit-list').append(el('div','audit-line '+f.severity,`${variant.title}${f.slide?' · слайд '+f.slide:''}: ${f.message}`));}if(job.warnings?.length)$('#audit-list').append(warningList(job.warnings));$('#audit-list').append(el('div','audit-line warning',job.contextual_audit.status==='completed'?'Контекстуальная проверка текста моделью выполнена.':'Контекстуальная проверка моделью не выполнена.'));for(const f of job.contextual_audit.findings||[])$('#audit-list').append(el('div','audit-line '+f.severity,f.message));$('#audit-list').append(el('div','audit-line warning',job.native_pptx_render?'PDF и предпросмотр отрисованы из готового PPTX через LibreOffice. Проверка дизайна человеком не выполняется автоматически.':'Предпросмотр построен из модели сцены, а не из PPTX: соответствие оформлению требует проверки.'));$('#results').scrollIntoView({behavior:'smooth',block:'start'});}
function updatePreview(){$('#preview-image').src=fileUrl(preview.id,`${preview.key}/slide-${preview.index}.png`);$('#slide-counter').textContent=`${preview.index} / ${preview.count}`;$('#prev-slide').disabled=preview.index===1;$('#next-slide').disabled=preview.index===preview.count;}
$('#prev-slide').onclick=()=>{preview.index--;updatePreview();};$('#next-slide').onclick=()=>{preview.index++;updatePreview();};$('#close-preview').onclick=()=>$('#preview-dialog').close();
$('#revise-form').addEventListener('submit',async event=>{event.preventDefault();if(!packageId)return;const button=event.target.querySelector('button');button.disabled=true;try{const job=await jsonPost(`/api/packages/${packageId}/revise`,{instructions:$('#revision').value});$('#prep-progress').hidden=false;$('#workspace').scrollIntoView({behavior:'smooth'});await watchPreparation(job.id,true);}catch(e){toast(e.message);}finally{button.disabled=false;}});
$('#nav-history').onclick=async()=>{$('#history').hidden=false;$('#history-list').replaceChildren();try{const jobs=await api('/api/jobs');for(const job of jobs){const row=el('div','history-item');const info=el('div');info.append(el('div','',job.kind==='preparation'?'Подготовка шаблона':'Три презентации'),el('small','',`${new Date(job.created*1000).toLocaleString('ru')} · ${job.state}`));row.append(info);if(['completed','needs_review'].includes(job.state)){const button=el('button','secondary','Открыть');button.onclick=()=>showResults(job);row.append(button);}else if(job.state==='ready'){const button=el('button','secondary','Использовать');button.onclick=()=>{displayProfile(job);$('#workspace').scrollIntoView({behavior:'smooth'});};row.append(button);}$('#history-list').append(row);}$('#history').scrollIntoView({behavior:'smooth'});}catch(e){toast(e.message);}};
$('#close-history').onclick=()=>$('#history').hidden=true;$('#nav-create').onclick=()=>$('#workspace').scrollIntoView({behavior:'smooth'});
$('#demo').onclick=async()=>{const r=await fetch('/static/demo.md');$('#content').value=await r.text();$('#content').dispatchEvent(new Event('input'));$('#audience').value='Руководители компании';$('#slides').value=10;$('#instructions').value='Сохранить все исходные факты. Не придумывать показатели.';dirty();toast('Загружены демонстрационные, вымышленные материалы. Они не относятся к реальной компании.');};
async function init(){try{const [health,refs]=await Promise.all([api('/api/health'),api('/api/references')]);$('#model-mode').textContent=health.model_mode==='extractive'?'Автономно · без LLM':`Модель: ${health.model_id}`;for(const ref of refs){const o=el('option','',ref.name);o.value=ref.id;$('#reference').append(o);}if(refs.length){$('#reference').value=refs[0].id;$('#reference').dispatchEvent(new Event('change'));}}catch(e){toast(e.message);}}init();
